name: .NET CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Lấy source code
      - name: Checkout code
        uses: actions/checkout@v4

      # Cài .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # Restore thư viện
      - name: Restore dependencies
        run: dotnet restore

      # Build project
      - name: Build
        run: dotnet build --no-restore --configuration Release

      # Chạy Unit Test (NUnit)
      - name: Run Tests
        run: dotnet test --no-build --verbosity normal